#FROM linuxserver/domoticz:latest
FROM domoticz/domoticz:2023-beta.15212
#FROM smeagolworms4/mqtt-explorer

ENV CONFIG_PATH=/data

CMD ["/opt/domoticz/domoticz"]
#CMD node node-server/server/dist/node-server/server/src/index.js \
#   --http-port=$HTTP_PORT \
#   --config-path=$CONFIG_PATH \
#   --http-user=$HTTP_USER \
#   --http-password=$HTTP_PASSWORD\
#   --ssl-key-path=$SSL_KEY_PATH\
#   --ssl-cert-path=$SSL_CERT_PATH
